---

baseurl: "/slides"
languageCode: "en-us"
title: "Cloud Native Evolution"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Going Cloud Native"
    notes: |

      In this section, we cover the evolution toward cloud native.
